# Generated by Django 6.0.2 on 2026-02-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('venue_name', models.CharField(blank=True, max_length=255)),
                ('venue_address', models.TextField(blank=True)),
                ('city', models.CharField(default='Sydney', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('source_website', models.CharField(max_length=100)),
                ('original_event_url', models.URLField()),
                ('status', models.CharField(choices=[('new', 'New'), ('updated', 'Updated'), ('inactive', 'Inactive'), ('imported', 'Imported')], default='new', max_length=20)),
                ('last_scraped_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
